### ISSUE TITLE
Can I use the TraceListener and AppSettings together ?

### ISSUE THREAD

**Issue by johnkattenhorn** [serilog-trace-listener/SerilogTraceListener#1]
Is something like this supposed to work ? 

`<add key="serilog:write-to:Trace" value="" />`

Can I confirm the app.config values for adding the tracelistener, is this correct ?

`<add name="Serilog" type="SerilogTraceListener.SerilogTraceListener, SerilogTraceListener" />`

**Comment by zaus** [comment]
https://github.com/serilog/serilog/wiki/AppSettings

I think the first part of what you proposed is aimed at configuring a _Sink_, rather than the _Listener_.  If it's anything like [adding a global trace listener for NLog](http://nlog-project.org/2010/09/02/routing-system-diagnostics-trace-and-system-diagnostics-tracesource-logs-through-nlog.html), then it would be just the second part you mentioned:

````
  <system.diagnostics>
    <!-- add global listener: http://msdn.microsoft.com/en-us/library/b0ectfxd(v=vs.100).aspx -->
    <trace>
      <listeners>
        <add name="serilog"/>
      </listeners>
    </trace>
    <sharedListeners>
      <add name="serilog" type="SerilogTraceListener.SerilogTraceListener, SerilogTraceListener"/>
    </sharedListeners>
  </system.diagnostics>
````

I actually have no idea if you can set up the listener via app.settings -- in the project unit test you instantiate a global listener that attaches the current logger:
https://github.com/serilog-trace-listener/SerilogTraceListener/blob/master/test/SerilogTraceListener.Tests/SerilogTraceListenerTests.cs#L30
I tried the `diagnostics` way above with no luck.

**Comment by nblumhardt** [comment]
Hi @johnkattenhorn (picking up the thread here to help out),

No, those two options won't work together - specifying them both means Serilog would write to the trace, and the trace would write back to Serilog....

If you still need a hand with anything here let me know; thanks @zaus for the input also.
