### ISSUE TITLE
Make newline formatting optional

### ISSUE THREAD

**Issue by newbyca** [serilog-trace-listener/SerilogTraceListener#12]
Regarding: https://github.com/serilog-trace-listener/SerilogTraceListener/commit/a1482b93b9b44f46d7c8b0aaadb3f9e4e080ac9c#diff-e8d07dcaf19bef89f9255665d7bd4676R35
- [ ] A boolean constructor option to toggle the newline behavior on or off (consider making default off)
- [ ] Use formats in place of Environment.NewLine like this:
  `
  static readonly string TraceDataMessageTemplate = "{TraceSource:l} {TraceEventType}: {TraceEventId} :{NewLine}{TraceData:l}";
  `

**Comment by newbyca** [comment]
Happy to pr if this makes sense :)

**Comment by nblumhardt** [comment]
Thanks for the ticket. The second option (`{NewLine}`) and accepting a template argument sounds like the way to go. I haven't spent a lot of time with this codebase, so I could be missing something, but I think a PR for that option would be on the mark :+1:

**Comment by sgryphon** [comment]
Rather than having a hard coded format, with one boolean to toggle between two variations, I have put in a PR to get rid of the hard coded formats, allowing the user to decide what format they want.

This means that when a developer traces (... "level={0} user={1}", 5, Thread.CurrentPrincipal.Identity.Name), then they get a message "level=5 user=Alice", not some hard coded format with several prefix values that they may or may not want.

All the properties are still logged, so if the developer does want the output, say to a console or file, then they can specify the format however they want; not only with or without whatever newlines they like, but any other format as well.

**Comment by sgryphon** [comment]
This is now effectively fixed as the hardcoded formats have been completely removed, so whether you want newlines or not is entirely up to the user how they configure the sink template format.
